import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import ProductsDisplay from "@/components/ProductsDisplay";
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import SideNav from "@/components/sideNav";

import Homee from "./Home";

import { strorefront } from "../utils";

export default function Index({ products }) {
  console.log({ products });
  return (
    <div>
      <Head>
        <title>Bubble Boots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Homee/>
      </main>
    </div>
  );
}
