import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


import Homee from "./Home";


export default function Index({ products }) {
  console.log({ products });
  return (
    <div>
      <Head>
        <title>Bubble Boots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Homee/>
      </main>
    </div>
  );
}
